# Generated by Django 5.2 on 2025-09-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'section'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
    ]
