# Generated by Django 5.2 on 2025-09-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['name'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
    ]
